name: petlove
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase packages (latest resolvable versions that work together)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.7
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5

  # Other packages
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  provider: ^6.1.2
  convex_bottom_bar: ^3.2.0
  # fluttertoast: ^8.2.8
  file_picker: ^8.0.7
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  geoflutterfire2: ^2.3.15
  cached_network_image: ^3.4.0
  # maps_launcher: ^2.2.0
  url_launcher: ^6.3.0 
  font_awesome_flutter: ^10.7.0


  path: any

    # Add the Gemini package
  google_generative_ai: ^0.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
